version: '3.6'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    build: ./mysql
    environment:
      MYSQL_DATABASE: "testdb"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - mysql_db:/var/lib/mysql
  back:
    image: openjdk:8
    container_name: back
    build: ./back
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ./back/spring_project:/app:cached
    working_dir: /app
  front:
    container_name: front
    build: ./front
    ports:
      - 9000:8080
    volumes:
      - ./front/vue_project:/app:cached
    stdin_open: true
    tty: true
volumes:
  mysql_db:
    driver: local